### ISSUE TITLE
Atag One do not work with Homey 2.0.0

### ISSUE THREAD

**Issue by HenkP207** [magtimmermans/com.cyclone-software.atagone#2]
Today I have installed Homey 2.0.0 and Atag One App doesn't work any more. 

Hi!

Helaas is je app gecrashed toen ik het volgende deed:

(...)

Dit is de stack trace:/drivers/atagone/driver.js:116
        var ao = new AtagOne(devices[args.device.id].data.ip);
                                                     ^

TypeError: Cannot read property 'data' of undefined
    at Object.<anonymous> (/drivers/atagone/driver.js:116:54)
    at emitThree (events.js:136:13)
    at Object.emit (events.js:217:7)
    at Homey.client.on (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v1/manager/flow.js:1:285)
    at eventListeners.filter.forEach.t (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v1/helpers/client.js:1:1008)
    at Array.forEach (<anonymous>)
    at process.on.e (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v1/helpers/client.js:1:985)
    at emitTwo (events.js:126:13)
    at process.emit (events.js:214:7)
    at emit (internal/child_process.js:762:12)

![atag one](https://user-images.githubusercontent.com/46729018/51212649-56a45d80-1919-11e9-996a-261239eb1454.png)

**Comment by magtimmermans** [comment]
Today there will be an update to the beta branch

**Comment by magtimmermans** [comment]
Beta version published
